In [46]:
import numpy as np

In [47]:
# Arrays

In [48]:
s = np.array(5)
s.shape

()

In [49]:
x = s + 3
print(x, type(x))

8 <class 'numpy.int32'>


In [50]:
v = np.array([1,2,3])
v.shape


(3,)

In [51]:
# Matrices

In [52]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])
m.shape

(3, 3)

In [53]:
# Tensors

In [54]:
t = np.array([[[[1,2,3], [4,5,6], [7,8,9]]],[[[1,2,3], [4,5,6], [7,8,9]]]])
t.shape

(2, 1, 3, 3)

In [55]:
# Changing Shapes

In [56]:
v = np.array([1,2,3,4])
v.shape

(4,)

In [57]:
a = v.reshape(1,4)
a

x = v[None, :]
x

y = v[:, None]
y.shape

(4, 1)

In [58]:
# Element-wise operations in numpy

In [59]:
values = np.array([1,2,3,4,5])
values *= 5
values

array([ 5, 10, 15, 20, 25])

In [60]:
# Element-wise Matrix Operations

In [61]:
v1 = np.array([1,2,3])
v2 = np.array([1,2,3])
v1*v2

array([1, 4, 9])

In [62]:
a = np.array([[1,3], [5,7]])
a.shape

b = np.array([[1,2,3], [4,5,6], [7,8,9]])
b.shape

#c = a + b

(3, 3)

In [63]:
# Data in the left matrix should be arranged as rows., while data in the right matrix should be arranged as columns.

In [64]:
# Matrix Product

In [65]:
a = np.array([[1,2,4], [1,2,3]])
b = np.array([[3,4,2], [4,5,6], [1,2,3]])
print(a.dot(b))
print(np.dot(a,b))
print(np.matmul(a,b))

[[15 22 26]
 [14 20 23]]
[[15 22 26]
 [14 20 23]]
[[15 22 26]
 [14 20 23]]


In [66]:
# Always store data as row-wise

In [68]:
#a.transpose()
a.T

array([[1, 1],
       [2, 2],
       [4, 3]])

In [ ]:
# # Use the numpy library
# import numpy as np


# def prepare_inputs(inputs):
#     # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
#     #       assign it to input_array
#     input_array = None
    
#     # TODO: find the minimum value in input_array and subtract that
#     #       value from all the elements of input_array. Store the
#     #       result in inputs_minus_min
#     inputs_minus_min = None

#     # TODO: find the maximum value in inputs_minus_min and divide
#     #       all of the values in inputs_minus_min by the maximum value.
#     #       Store the results in inputs_div_max.
#     inputs_div_max = None

#     # return the three arrays we've created
#     return input_array, inputs_minus_min, inputs_div_max
    

# def multiply_inputs(m1, m2):
#     # TODO: Check the shapes of the matrices m1 and m2. 
#     #       m1 and m2 will be ndarray objects.
#     #
#     #       Return False if the shapes cannot be used for matrix
#     #       multiplication. You may not use a transpose
#     pass


#     # TODO: If you have not returned False, then calculate the matrix product
#     #       of m1 and m2 and return it. Do not use a transpose,
#     #       but you swap their order if necessary
#     pass
    

# def find_mean(values):
#     # TODO: Return the average of the values in the given Python list
#     pass


# input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])
# print("Input as Array: {}".format(input_array))
# print("Input minus min: {}".format(inputs_minus_min))
# print("Input  Array: {}".format(inputs_div_max))

# print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
# print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
# print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

# print("Mean == {}".format(find_mean([1,3,4])))

In [171]:
# Numpy Quiz

import numpy as np

inputs = [1,2,3]
def prepare_inputs(inputs):
    
    # TODO 1
    input_array = np.array([inputs])
    
    # TODO 2
    inputs_minus_min = input_array - np.min(input_array)
    
    # TODO 3
    inputs_div_max = inputs_minus_min / np.max(inputs_minus_min)
    
    return input_array, inputs_minus_min, inputs_div_max
    



def multiply_inputs(m1, m2):
    print(m1.shape, m2.shape)
    if m1.shape[-1] == m2.shape[0]:
        return m1.dot(m2)
    if m1.shape[0] ==  m2.shape[-1]:
        return m2.dot(m1)
    if m1.shape[-1] != m2.shape[0]:
        return False
    
def find_mean(values):
    return np.mean(values)


input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])
print("Input as Array: {}".format(input_array))
print("Input minus min: {}".format(inputs_minus_min))
print("Input  Array: {}".format(inputs_div_max))

print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

print("Mean == {}".format(find_mean([1,3,4])))




Input as Array: [[-1  2  7]]
Input minus min: [[0 3 8]]
Input  Array: [[0.    0.375 1.   ]]
(2, 3) (4, 1)
Multiply 1:
False
(2, 3) (3, 1)
Multiply 2:
[[14]
 [32]]
(2, 3) (1, 2)
Multiply 3:
[[ 9 12 15]]
Mean == 2.6666666666666665


In [172]:
# Solution
# Use the numpy library
import numpy as np


######################################################
#
#      MESSAGE TO STUDENTS:
#
#  This file contains a solution to the coding quiz. Feel free
#  to look at it when you are stuck, but try to solve the
#   problem on your own first.
#
######################################################


def prepare_inputs(inputs):
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to input_array
    input_array = np.array([inputs])
    
    # TODO: find the minimum value in input_array and subtract that
    #       value from all the elements of input_array. Store the
    #       result in inputs_minus_min
    # We can use NumPy's min function and element-wise division
    inputs_minus_min = input_array - np.min(input_array)

    # TODO: find the maximum value in inputs_minus_min and divide
    #       all of the values in inputs_minus_min by the maximum value.
    #       Store the results in inputs_div_max.
    # We can use NumPy's max function and element-wise division
    inputs_div_max = inputs_minus_min / np.max(inputs_minus_min)

    return input_array, inputs_minus_min, inputs_div_max
    

def multiply_inputs(m1, m2):
    # Check the shapes of the matrices m1 and m2. 
    # m1 and m2 will be ndarray objects.
    #
    # Return False if the shapes cannot be used for matrix
    # multiplication. You may not use a transpose
    if m1.shape[0] != m2.shape[1] and m1.shape[1] != m2.shape[0]:     
        return False

    # Have not returned False, so calculate the matrix product
    # of m1 and m2 and return it. Do not use a transpose,
    #       but you swap their order if necessary
    if m1.shape[1] == m2.shape[0]:
        return np.matmul(m1, m2)        
    else:
        return np.matmul(m2, m1)        


def find_mean(values):
    # Return the average of the values in the given Python list
    # NumPy has a lot of helpful methods like this.
    return np.mean(values)

print("Input as Array: {}".format(input_array))
print("Input minus min: {}".format(inputs_minus_min))
print("Input  Array: {}".format(inputs_div_max))

print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

print("Mean == {}".format(find_mean([1,3,4])))



Input as Array: [[-1  2  7]]
Input minus min: [[0 3 8]]
Input  Array: [[0.    0.375 1.   ]]
Multiply 1:
False
Multiply 2:
[[14]
 [32]]
Multiply 3:
[[ 9 12 15]]
Mean == 2.6666666666666665
